import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { api } from "../../lib/api/client";

export function ConfigureFitosPage() {
  const [draftId, setDraftId] = useState<string>(); const [form, setForm] = useState({ contactName: "", businessName: "", email: "", phone: "", country: "Kenya", businessType: "Gym", needs: "" }); const [submitted, setSubmitted] = useState(false);
  const save = useMutation({ mutationFn: (submit: boolean) => (submit ? api.submitImplementationInquiry : api.saveImplementationInquiryDraft)({ id: draftId, contactName: form.contactName, businessName: form.businessName, email: form.email, phone: form.phone, country: form.country, businessType: form.businessType, payload: { needs: form.needs } }), onSuccess: (result) => { setDraftId(result.id); if (result.status === "submitted") setSubmitted(true); } });
  if (submitted) return <main className="public-page" style={{ padding: "5rem 2rem", textAlign: "center" }}><h1>We have your FITOS setup brief.</h1><p>Our implementation team will review it before any tenant is created.</p><Link to="/">Return home</Link></main>;
  return <main className="public-page" style={{ maxWidth: "42rem", margin: "auto", padding: "3rem 1.5rem" }}><Link to="/">← FITOS</Link><h1>Configure FITOS for your business</h1><p>Tell us how you operate. Save a draft at any point; no tenant is created until reviewed.</p><form className="form-stack" onSubmit={(e) => { e.preventDefault(); save.mutate(true); }}>{([['contactName','Your name'],['businessName','Business name'],['email','Work email'],['phone','Phone / WhatsApp'],['country','Country'],['businessType','Business type']] as const).map(([key,label]) => <label key={key}>{label}<input required={key === 'contactName' || key === 'businessName' || key === 'email'} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<label>What do you need FITOS to help with?<textarea value={form.needs} onChange={(e) => setForm({ ...form, needs: e.target.value })} /></label><div style={{ display: "flex", gap: ".75rem" }}><button type="button" onClick={() => save.mutate(false)}>Save draft</button><button type="submit" disabled={save.isPending}>Submit setup brief</button></div>{save.error && <p role="alert">Unable to save. Please try again.</p>}</form></main>;
}
